In [1]:
import numpy as np

In [19]:
#1- Converta os elementos do array [3, 5, 9, 16, 25] para float.

array1 = np.array([3, 5, 9, 16, 25])
array_convert_float = array1.astype(np.float64)
print(array_convert_float)

array([ 3.,  5.,  9., 16., 25.])

In [78]:
#2- Dado o array [1.2, -3.6, 8.99999, 16.1], converta os seus elementos para int.

array2 = np.array([1.2, -3.6, 8.99999, 16.1])
array_convert_int = array2.astype(np.int32)
print(array_convert_int)

[ 1 -3  8 16]


In [77]:
#3- Crie uma matriz 3x9 contendo apenas elementos com valor zero.

matriz_zero_int = np.zeros([3, 9], dtype = np.int32)
print(matriz_zero_int)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [76]:
#4- Crie uma matriz 6x7 de números inteiros contendo elementos com valor 1.

matriz_um_int = np.ones([6, 7], dtype = np.int32)
print(matriz_um_int)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [31]:
#5- Crie uma matriz identidade de tamanho 4

matriz_identidade = np.eye(4)
print(matriz_identidade)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [72]:
#6- Crie um array de números aleatórios entre 0 e 1 de tamanho 5.

array_ale_int = np.random.randint(2, size = 5) 
print(array_ale_int)

[1 1 0 0 0]


In [3]:
#7 Crie uma matriz 3x6 contendo números aleatórios de 0 a 5 (0, 1, 2, 3, 4, 5).

matriz_ale_int = np.random.randint(6, size = (3, 6)) 
print(matriz_ale_int)

[[4 2 2 1 4 0]
 [3 3 2 4 0 0]
 [4 2 0 3 2 0]]


In [3]:
#Considere a seguinte matriz para os exercícios 8 a 11:
#[[4 6 8]
#[-4 3 2]
#[22 -15 12]]

matriz_8_11 = np.array([
    [4, 6, 8], 
    [-4, 3, 2], 
    [22, -15, 12]])

array([[  4,   6,   8],
       [ -4,   3,   2],
       [ 22, -15,  12]])

In [4]:
#8 Informe o código para exibir o valor máximo da matriz.

print(matriz_8_11.max())

22


In [5]:
#9 Qual o código para exibir o valor mínimo da matriz?

print(matriz_8_11.min())

-15


In [6]:
#10 Como fazer para imprimir na tela a soma dos elementos da matriz?

print(matriz_8_11.sum())

38


In [7]:
#11 Escreva o código necessário para exibir a média dos elementos da matriz.

print(matriz_8_11.mean())

4.222222222222222


In [8]:
#Considere o seguinte array para os exercícios 12 a 16.
#[13 -2 6 8 23 15 3 90 4 10 56 12]

array_12_16 = np.array([1, -2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12])

array([ 1, -2,  6,  8, 23, 15,  3, 90,  4, 10, 56, 12])

In [23]:
#12 Exibir o 4º elemento do array.

print(array_12_16[3])

8


In [24]:
#13 Exibir os 3 últimos elementos do array.

print(array_12_16[-3:])

[10 56 12]


In [26]:
#14 Exibir os elementos a partir da posição 2.

print(array_12_16[2:])

[ 6  8 23 15  3 90  4 10 56 12]


In [79]:
#15 Exibir um array entre o 2º e o 6º elementos. O 6º elemento deve estar presente.

print(array_12_16[1:6])

[-2  6  8 23 15]


In [82]:
#16 Escreva o código que resulta na exibição do seguinte array: [23 15 3 90] 

print(array_12_16[4:8])

[23 15  3 90]


In [65]:
#Considere a seguinte matriz para os exercícios de 16 a 20
#	[[1	3	16	 -25	14]
#	 [2	0	10	5	17]
#	 [19	4	8	15	13]
#	 [7	12	-5	14	0]]

matriz_17_20 = np.array([
    [1, 3, 16, -25, 14],
    [2, 0, 10, 5, 17],
    [19, 4, 8, 15, 13],
    [7, 12, -5, 14, 0]])

In [30]:
#17 Escreva o código para exibir a 3ª linha da matriz.

print(matriz_17_20[2])

[19  4  8 15 13]


In [32]:
#18 Escreva o código para exibir a 4ª coluna

print(matriz_17_20[:, 3])

[-25   5  15  14]


In [67]:
#19 Escreva o código para exibir o elemento de valor 10.

indices = np.where(matriz_17_20 == 10)
print(matriz_17_20[indices])

[10]


In [73]:
#20 Escreva o código que resulta na seguinte matriz:
#    [[0	10	5]
#     [4	8	15]]

print(matriz_17_20[1:3, 1:4])

[[ 0 10  5]
 [ 4  8 15]]


In [75]:
#21 Dada a seguinte matriz:
#	[[2	-1	15	24]
#	[-3	18	4	25]
#	[9	10	-13	7]]

#Crie uma nova matriz, atribuindo o valor 1 para os números ímpares, e 2, para os números pares, utilizando a biblioteca numpy.
matriz_21 = np.array([
    [2, -1, 15, 24],
    [-3, 18, 4, 25],
    [9, 10, -13, 7]
])

matriz_nova = np.where(matriz_21 % 2 == 0, 2, 1)
print(matriz_nova)

[[2 1 1 2]
 [1 2 2 1]
 [1 2 1 1]]
