In [1]:
import numpy as np

In [19]:
#1- Converta os elementos do array [3, 5, 9, 16, 25] para float.
array1 = np.array([3, 5, 9, 16, 25])
array_convert_float = array1.astype(np.float64)
print(array_convert_float)

array([ 3.,  5.,  9., 16., 25.])

In [25]:
#2- Dado o array [1.2, -3.6, 8.99999, 16.1], converta os seus elementos para int.
array2 = np.array([1.2, -3.6, 8.99999, 16.1])
array_convert_int = array2.astype(np.int32)
print(array_convert_int)

In [26]:
#3- Crie uma matriz 3x9 contendo apenas elementos com valor zero.
matriz_zero_int = np.zeros([3, 9], dtype = np.int32)
print(matriz_zero_int)

In [27]:
#4- Crie uma matriz 6x7 de números inteiros contendo elementos com valor 1.
matriz_um_int = np.ones([6, 7], dtype = np.int32)
print(matriz_um_int)

In [31]:
#5- Crie uma matriz identidade de tamanho 4.
matriz_identidade = np.eye(4)
print(matriz_identidade)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [72]:
#6- Crie um array de números aleatórios entre 0 e 1 de tamanho 5.
array_ale_int = np.random.randint(2, size = 5) 
print(array_ale_int)

[1 1 0 0 0]
